root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  delay = 800
  exclude_dir = ["tmp", "uploads", "vendor"]
  exclude_regex = ["_test\\.go"]
  include_ext = ["go", "yaml"]
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
