server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location / { try_files $uri $uri/ /index.html; }
    location /shared/ { alias /usr/share/nginx/html/shared/; }
    location /api/ {
        proxy_pass http://host.docker.internal:4008/api/;
        proxy_set_header Host $host;
    }
}
